### ISSUE TITLE
Purpose of meta_json addition

### ISSUE THREAD

**Issue by marcciosilva** [shariq/notion-on-firebase#2]
Hi, how are you @shariq? 

I'm attempting to use this project for the purpose it was built for, and even though I get it to work quite well with commit 68d465988378f24e74f8dd098919031d3fcfa2f4, I can't quite get the purpose of the new meta_json dictionary (now required in commit f514ab1568d5ac7f4af5411a7cf91ac298f5e517) - is it to define the page -> short_url mapping without requiring the user to give it as an input?
Could you show me a sample meta_json dictionary?

Thank you!

**Comment by michaellatman** [comment]
@shariq Can we get an answer for this?

**Comment by shariq** [comment]
Here's an example meta.json file:
https://github.com/shariq/shar.iq/blob/master/meta.json

Sorry, didn't notice this earlier!

**Comment by michaellatman** [comment]
```
Traceback (most recent call last):
  File "/Users/mlatman/dev/TesPlayerHelp/spider.py", line 31, in notion_spider
    html, new_pages = notion.scrape_notion_page(page, meta_json=meta_json)
  File "/Users/mlatman/dev/TesPlayerHelp/notion.py", line 130, in scrape_notion_page
    login_element = driver.find_element_by_xpath('//a[@href="/login"]')
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//a[@href="/login"]"}
  (Session info: chrome=74.0.3729.108)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Linux 4.9.93-linuxkit-aufs x86_64)

skipping f6fd2f0085c34dbbaaef44db8924ee4f for now
postprocessing site/public/f6fd2f0085c34dbbaaef44db8924ee4f.html ...
Traceback (most recent call last):
  File "run.py", line 97, in <module>
    main(notion_root, firebase_path, meta_json)
  File "run.py", line 55, in main
    rewrites = spider.run(root_page, results_path=firebase_public_path, meta_json=meta_json)
  File "/Users/mlatman/dev/TesPlayerHelp/spider.py", line 95, in run
    postprocess(results_path)
  File "/Users/mlatman/dev/TesPlayerHelp/spider.py", line 73, in postprocess
    'https://www.notion.so/' + page, '/' + short_url)
TypeError: cannot concatenate 'str' and 'bool' objects
1 selenium server(s) found
found selenium container to destroy
peaceful_stonebraker
peaceful_stonebraker
```
Any ideas?

**Comment by shariq** [comment]
Hey Michael, you can probably just remove the line referring to removing the login element since the Notion page layout was changed. Sorry I'm not maintaining this code any longer
