### ISSUE TITLE
Received a selenium error

### ISSUE THREAD

**Issue by vaibhavviswanathan** [shariq/notion-on-firebase#3]
page title: Scrapbook
encountered error while scraping d065149ff38a4e7a9b908aeb262b0f4f
Traceback (most recent call last):
  File "/home/vai/web/notion-on-firebase/spider.py", line 31, in notion_spider
    html, new_pages = notion.scrape_notion_page(page, meta_json=meta_json)
  File "/home/vai/web/notion-on-firebase/notion.py", line 130, in scrape_notion_page
    login_element = driver.find_element_by_xpath('//a[@href="/login"]')
  File "/home/vai/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/home/vai/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/vai/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/vai/.local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//a[@href="/login"]"}
  (Session info: chrome=79.0.3945.117)

**Comment by shariq** [comment]
Hey Vaibhav, I haven't kept this repo up to date but you can probably just remove the line which tries to remove the login element.
